spring:
  redis:
    database: 0
    host: #
    port: 6381
    password: #
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: #
      username: #
      password: #
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.immouo.gateway.entity.po

